//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trino.WPF.ProjetoFinal.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string DocumentNumber { get; set; }
        public string Address { get; set; }
        public Nullable<int> AddressNumber { get; set; }
        public Nullable<System.Guid> CityId { get; set; }
    
        public virtual City City { get; set; }
    }
}
